# Generated by Django 4.1.3 on 2022-12-12 21:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quadshop', '0005_billingaddress_order_billing_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
