# Generated by Django 4.1.3 on 2022-12-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quadshop', '0007_color_size_product_variant_choice_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='code',
        ),
    ]
