# Generated by Django 4.1.3 on 2022-12-14 22:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quadshop', '0008_remove_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
