# Generated by Django 4.1.3 on 2022-12-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quadshop', '0011_alter_userprofile_address_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='size_id',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='image_id',
        ),
    ]
